// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdBje3wjjQP6_j8z-rw4ajjVCw5HeFOdo',
    appId: '685301331456:web:c0dceed8a500179e75cae5',
    messagingSenderId: '685301331456',
    projectId: 'wisali-thailand',
    authDomain: 'wisali-thailand.firebaseapp.com',
    databaseURL: 'https://wisali-thailand-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wisali-thailand.appspot.com',
    measurementId: 'G-FZRNTYZVL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdBje3wjjQP6_j8z-rw4ajjVCw5HeFOdo',
    appId: '685301331456:web:c0dceed8a500179e75cae5',
    messagingSenderId: '685301331456',
    projectId: 'wisali-thailand',
    databaseURL: 'https://wisali-thailand-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wisali-thailand.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9jcPlOB4KvZi5bCLRc6Arru3r-bMV_W4',
    appId: '1:685301331456:ios:03408200202a157375cae5',
    messagingSenderId: '607429994423',
    projectId: 'wisali-thailand',
    databaseURL: 'https://wisali-thailand-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wisali-thailand.appspot.com',
    androidClientId: '607429994423-3hj4tdv43i5cvvf3bi1p4hgsicqgqt7b.apps.googleusercontent.com',
    iosClientId: '607429994423-vhegm48bier79nl098f757jkte93rflu.apps.googleusercontent.com',
    iosBundleId: 'com.wisali.customer',
  );
}
